#!/usr/bin/env bash
set -euo pipefail

# Refresh a short-lived Infisical access token from machine identity credentials.
# Output: /home/D31337m3/Orm_d31337m3/.env.infisical.runtime.generated

ROOT_DIR="/home/D31337m3/Orm_d31337m3"
STATIC_ENV_FILE="${ROOT_DIR}/.env.infisical.runtime"
MACHINE_ENV_FILE="${ROOT_DIR}/.env.infisical.machine"
OUT_ENV_FILE="${ROOT_DIR}/.env.infisical.runtime.generated"

log() {
  printf "[%s] %s\n" "$(date '+%Y-%m-%d %H:%M:%S')" "$*"
}

# Load static runtime defaults first.
if [[ -f "${STATIC_ENV_FILE}" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "${STATIC_ENV_FILE}"
  set +a
fi

# Load machine identity creds if present.
if [[ -f "${MACHINE_ENV_FILE}" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "${MACHINE_ENV_FILE}"
  set +a
fi

INFISICAL_SITE_URL="${INFISICAL_SITE_URL:-https://app.infisical.com}"
INFISICAL_ENVIRONMENT="${INFISICAL_ENVIRONMENT:-prod}"
INFISICAL_PROJECT_ID="${INFISICAL_PROJECT_ID:-}"
INFISICAL_SECRETS_PATH="${INFISICAL_SECRETS_PATH:-/}"

minted_token=""

if [[ -n "${INFISICAL_CLIENT_ID:-}" && -n "${INFISICAL_CLIENT_SECRET:-}" ]]; then
  log "Attempting to mint short-lived token via Universal Auth"

  if minted_token="$(INFISICAL_SITE_URL="${INFISICAL_SITE_URL}" INFISICAL_CLIENT_ID="${INFISICAL_CLIENT_ID}" INFISICAL_CLIENT_SECRET="${INFISICAL_CLIENT_SECRET}" python3 - <<'PY'
import json
import os
import sys
import urllib.request

site = os.environ['INFISICAL_SITE_URL'].rstrip('/')
url = f"{site}/api/v1/auth/universal-auth/login"
payload = {
    "clientId": os.environ['INFISICAL_CLIENT_ID'],
    "clientSecret": os.environ['INFISICAL_CLIENT_SECRET'],
}

req = urllib.request.Request(
    url,
    data=json.dumps(payload).encode('utf-8'),
    headers={"Content-Type": "application/json"},
    method="POST",
)

try:
    with urllib.request.urlopen(req, timeout=15) as resp:
        raw = resp.read().decode('utf-8')
except Exception as exc:
    print(f"ERROR:{exc}")
    sys.exit(2)

try:
    data = json.loads(raw)
except Exception:
    print("ERROR:invalid-json")
    sys.exit(3)

# Support a few response shapes.
token = (
    data.get('accessToken')
    or data.get('token')
    or (data.get('data') or {}).get('accessToken')
    or (data.get('data') or {}).get('token')
)

if not token:
    print("ERROR:no-token-in-response")
    sys.exit(4)

print(token)
PY
)"; then
    :
  else
    log "Failed to mint token from machine identity; will try fallback token"
    minted_token=""
  fi
fi

if [[ -z "${minted_token}" ]]; then
  if [[ -n "${INFISICAL_SERVICE_TOKEN:-}" ]]; then
    log "Using fallback static service token from ${STATIC_ENV_FILE}"
    minted_token="${INFISICAL_SERVICE_TOKEN}"
  else
    log "No minted token and no fallback service token available"
    exit 1
  fi
fi

umask 077
cat > "${OUT_ENV_FILE}" <<EOF
# Auto-generated by refresh_infisical_access_token.sh
INFISICAL_SITE_URL=${INFISICAL_SITE_URL}
INFISICAL_ENVIRONMENT=${INFISICAL_ENVIRONMENT}
INFISICAL_PROJECT_ID=${INFISICAL_PROJECT_ID}
INFISICAL_SECRETS_PATH=${INFISICAL_SECRETS_PATH}
INFISICAL_SERVICE_TOKEN=${minted_token}
EOF

chmod 600 "${OUT_ENV_FILE}"
log "Wrote runtime token env: ${OUT_ENV_FILE}"
